version: '3.4'

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  secrets-app:
    image: secrets-app:latest
    container_name: secrets-app
    depends_on:
      - etcd
    environment:
      - ETCD_URLS=etcd:2379
      - GIT_REPO_URL=https://github.com/downfa11/secret-policy.git
      - AES_KEY=your-secret-aes-256-key-32bytes-
      - APP_HTTP_PORT=8080
    ports:
      - "8080:8080"
      - "50051:50051"
