version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    networks:
      - secret-network

 # docker build -t downfa11/secrets:latest --build-arg JAR_FILE=build/libs/secrets-0.0.1.jar .
  secrets:
    image: downfa11/secrets:latest
    depends_on:
      - etcd
    environment:
      - GIT_REPO_URL=https://github.com/downfa11/secret-policy
      - ETCD_URL=http://etcd:2379
      # POLICIES_LOCATION 명시안하면 root dir
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"
    networks:
      - secret-network
    stdin_open: true
    tty: true

networks:
  secret-network:
    driver: bridge
