services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2379:2379"
    networks:
      - secret-network

  etcd2:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      - secret-network

  etcd3:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      - secret-network

  secrets-master:
    image: downfa11/secrets:latest
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - SPRING_SHELL_INTERACTIVE_ENABLED=true
      - GIT_REPO_URL=https://github.com/downfa11/secret-policy
      - ETCD_URL=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379  # 복수 URL 지원여부 확인 필요
    volumes:
      - ./logs/secrets1:/logs
    ports:
      - "8080:8080"
    networks:
      - secret-network
    stdin_open: true
    tty: true

  secrets-worker-1:
    image: downfa11/secrets:latest
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - secrets.shell.enabled=false
      - GIT_REPO_URL=https://github.com/downfa11/secret-policy
      - ETCD_URL=http://etcd1:2379,http://etcd2:2380,http://etcd3:2381
    volumes:
      - ./logs/secrets-worker-1:/logs
    ports:
      - "8081:8080"
    networks:
      - secret-network
    stdin_open: true
    tty: true

  secrets-worker-2:
    image: downfa11/secrets:latest
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - secrets.shell.enabled=false
      - GIT_REPO_URL=https://github.com/downfa11/secret-policy
      - ETCD_URL=http://etcd1:2379,http://etcd2:2380,http://etcd3:2381
    volumes:
      - ./logs/secrets-worker-2:/logs
    ports:
      - "8082:8080"
    networks:
      - secret-network
    stdin_open: true
    tty: true

networks:
  secret-network:
    driver: bridge
