version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    networks:
      - secret-network

  secrets-server:
    image: downfa11/secrets-server:latest
    depends_on:
      - etcd
    environment:
      - GIT_REPO_URL=https://github.com/downfa11/secret-policy
      - ETCD_URL=http://etcd:2379
      # POLICIES_LOCATION 명시안하면 root dir
    volumes:
      - ./logs:/logs
      - ./certs:/certs
    ports:
      - "8080:8080"
    networks:
      - secret-network

  secrets-command:
    image: downfa11/secrets-command:latest
    environment:
      - SERVER_URL=http://secrets-server:8080
    volumes:
      - ./certs:/certs
    ports:
      - "8081:8080"
    networks:
      - secret-network
    stdin_open: true
    tty: true

networks:
  secret-network:
    driver: bridge
